Add zh_cn README
RustySamovar/RustySamovar pull request #3
Opened 2022-05-22 23:15 UTC by Searchstars

2022-05-23 10:05 UTC, Coooookies commented
我的建议是不要夹杂私货
The translation is too extreme

2022-05-23 10:24 UTC, Searchstars commented
> 我的建议是不要夹杂私货 The translation is too extreme

确实但这样或许会更有趣点（

2022-05-26 10:01 UTC, WetABQ requested changes
别魔怔
be normal plz

2022-05-26 10:01 UTC, WetABQ commented on README_CN.md
> +- 在windows上，请查看 [棺方文档](https://www.rust-lang.org/tools/install) （真心推荐使用Liunx！！！）
别传教
don't advertise or promote something else

2022-05-26 10:01 UTC, WetABQ commented on README_CN.md
> +就跟你躺在床上打飞机一样简单，执行 `cargo build` 即可
禁止魔怔翻译
don't translate it extremely

`Just plain and simple cargo build.` -> `执行 cargo build 即可`

2022-05-26 10:01 UTC, WetABQ commented on README_CN.md
> +- Windows上，别他妈告诉我你不会用Windows安装程序和openssh指令
不要攻击用户
Don't abuse or personal attack the user

Keep it to be `TODO`

2022-05-26 10:04 UTC, Searchstars commented
> 别魔怔 be normal plz

啊这，但是这个pr似乎没人理，然后pr发出后代码怎么改来着忘了（大佬教教呗

2022-05-26 10:07 UTC, Searchstars commented
OK刚刚改了
just changed

2022-05-26 15:40 UTC, WetABQ requested changes

2022-05-26 15:40 UTC, WetABQ commented on README_CN.md
> +- 在windows上，请查看 [棺方文档](https://www.rust-lang.org/tools/install)
`棺方文档` -> `官方文档`

2022-12-13 02:21 UTC, closed without merging